name: Development Build and Formating

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - '**/*.toml'
      - '**/*.rs'
      - '**/*.json'
      - '.github/workflows/**' 
  pull_request:
    paths:
      - '**/*.toml'
      - '**/*.rs'
      - '**/*.json'
      - '.github/workflows/**' 

env:
  CARGO_TERM_COLOR: always
  APP_VERSION: "2.0.1"

jobs:
  formating_code:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Formating code
    steps:
    - uses: actions/checkout@v4
    - name: Formating code
      run: cargo fmt
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Auto format code" || echo "No changes to commit"
        git push || echo "No changes to push"
        
  build_linux:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Build Linux
    steps:
    - uses: actions/checkout@v4
    - name: Build linux
      run: cargo build --release
    - name: Move linux binaries
      run: |
        mv target/release/FileSpliter FileSpliter
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-binaries
        path: |
          FileSpliter

  build_windows:
    runs-on: windows-latest
    permissions: write-all
    name: Build Windows
    steps:
    - uses: actions/checkout@v4
    - name: Build windows
      run: cargo build --release
    - name: Move windows binaries
      run: |
        move target\release\FileSpliter.exe FileSpliter.exe
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-binaries
        path: |
          FileSpliter.exe